-- 001_create_tables.sql
-- Mobil Katte — schema inti (compact tables)
-- Catatan: tax_expired_at disimpan sebagai TEXT agar cocok dengan tampilan
-- "15 Desember 2026" yang dipakai UI tanpa perubahan format.

-- ============ brands ============
create table public.brands (
  id         int generated by default as identity primary key,
  name       text not null unique,
  created_at timestamptz not null default now()
);

-- ============ cars ============
create table public.cars (
  id            bigint generated by default as identity primary key,
  slug          text not null unique,
  brand_id      int not null references public.brands(id) on delete restrict,
  name          text not null,
  type          text not null default '',
  year          int not null,
  price         bigint not null,
  mileage       int not null default 0,
  transmission  text not null default 'Automatic',
  fuel          text not null default 'Bensin',
  color         text not null default '',
  tax_status    text not null default 'Aktif',
  tax_expired_at text,
  condition     text not null default 'Bekas',
  location      text not null default '',
  plate         text not null default '',
  video_url     text,
  description   text not null default '',
  status        text not null default 'Tersedia',
  featured      boolean not null default false,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now(),
  deleted_at    timestamptz
);

create index idx_cars_brand on public.cars(brand_id);
create index idx_cars_status on public.cars(status);
create index idx_cars_deleted on public.cars(deleted_at);
create index idx_cars_featured on public.cars(featured) where deleted_at is null;

-- ============ car_photos ============
create table public.car_photos (
  id         bigint generated by default as identity primary key,
  car_id     bigint not null references public.cars(id) on delete cascade,
  photo_url  text not null,
  sort_order int not null default 0
);

create index idx_car_photos_car on public.car_photos(car_id, sort_order);

-- ============ admins ============
create table public.admins (
  id            int generated by default as identity primary key,
  email         text not null unique,
  password_hash text not null,
  name          text not null default 'Administrator',
  created_at    timestamptz not null default now()
);

-- ============ settings ============
create table public.settings (
  key        text primary key,
  value      text not null,
  updated_at timestamptz not null default now()
);

-- ============ updated_at trigger ============
create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

create trigger cars_touch_updated
  before update on public.cars
  for each row execute function public.touch_updated_at();