-- 007_sell_offers.sql
-- Mobil Katte — tabel penawaran mobil dari user (user menawarkan mobilnya dibeli admin).
-- Foto disimpan sebagai base64 data URL di sell_offer_photos (konsisten dengan car_photos).

-- ============ sell_offers ============
create table public.sell_offers (
  id           bigint generated by default as identity primary key,
  brand        text not null default '',
  name         text not null default '',
  type         text not null default '',
  year         int,
  price        bigint,
  mileage      int not null default 0,
  transmission text not null default '',
  fuel         text not null default '',
  color        text not null default '',
  tax_status   text not null default 'Aktif',
  location     text not null default '',
  plate        text not null default '',
  description  text not null default '',
  seller_name  text not null default '',
  seller_phone text not null default '',
  seller_email text,
  status       text not null default 'Baru',
  admin_note   text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),
  deleted_at   timestamptz
);

create index idx_sell_offers_status on public.sell_offers(status);
create index idx_sell_offers_deleted on public.sell_offers(deleted_at);

-- ============ sell_offer_photos ============
create table public.sell_offer_photos (
  id         bigint generated by default as identity primary key,
  offer_id   bigint not null references public.sell_offers(id) on delete cascade,
  photo_url  text not null,
  sort_order int not null default 0
);

create index idx_sell_offer_photos_offer on public.sell_offer_photos(offer_id, sort_order);

-- ============ updated_at trigger ============
create trigger sell_offers_touch_updated
  before update on public.sell_offers
  for each row execute function public.touch_updated_at();

-- ============ RLS ============
-- API menggunakan service role key (bypass RLS). Tidak ada policy publik agar
-- data penawaran tidak bisa dibaca/ditulis dari client tanpa autentikasi admin.
alter table public.sell_offers enable row level security;
alter table public.sell_offer_photos enable row level security;
